name: test-workflow
on: [push]

jobs:
    test:
        name: ${{ github.actor }} is learning GitHub Actions
        runs-on: ubuntu-latest
        steps:
            - name: Testing
              run: echo "Github Action Testing"
