name: test-workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Testing
            run: echo "Github Action Testing"
